// <auto-generated />
using System;
using BHAMCApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BHAMCApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201112072810_FKB2020")]
    partial class FKB2020
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("BHAMCApp.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("BHAMCApp.Models.Bhamc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AntenatalCare")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateMenstruation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GestationalAge")
                        .HasColumnType("TEXT");

                    b.Property<string>("HospitalName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterviewerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ10")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ13")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ15")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ18")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ20")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ22_4")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ3")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ35")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ36")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ4")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ56")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ67")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ70_4")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ90")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ92")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostNatalCare")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Q1")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q10")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q100_1_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q100_5_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q100_6_1")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q102")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q103")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q11")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q12_7")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q13")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q14")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q15")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q16")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q17")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q18")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q19")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q20")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q21")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q22_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q22_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q22_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q22_4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q23")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Q24")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q25")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q26")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q27")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q28")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q29")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q3")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q30")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q31")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q32")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q32_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q33")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q34")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q35")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q36")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q37")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Q38")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q39")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q4")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q40")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q41")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q42")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q43_6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q44")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q45")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q46")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q47")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q48")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q49")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q5")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q50")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Q51")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q52")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q53")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q54")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Q54_1")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Q54_2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q54_3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q54_4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q55")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q56")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q56_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q56_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q56_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q56_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q56_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q58_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q58_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q58_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q58_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q59_6")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q60")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Q60_1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q60_2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q60_3")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Q61_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q61_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q61_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q61_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q61_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q61_6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q62")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q63")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Q64_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q64_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q64_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q64_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q64_5")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q65")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q66")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q67")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q68")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q68Yes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q69")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q70_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q70_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q70_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q70_4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q71")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q71_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q72")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q73")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q74")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q75")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q76")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q77")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q78")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q79")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q8")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q80")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q81_6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q82_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q82_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q82_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q82_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q82_5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q83")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q84")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q85")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q86")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q87")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q88")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q89")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q9")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q90")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q91")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q92")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q93")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q94")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q95")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q96")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q97")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q98_6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q99_1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q99_2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q99_3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q99_4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Q99_5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QEA100")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QEC100")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QECO100")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QECOO100")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionnaireNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("QuestionnaireNo")
                        .IsUnique();

                    b.ToTable("Bhamc");
                });

            modelBuilder.Entity("BHAMCApp.Models.FKBABA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFollowup")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("IDNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagementFT")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemsDiagnosis")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q10_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q10_2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q10_3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q10_4")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q1_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q2_1")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q4")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q5")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q7")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q9")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("FKBABA");
                });

            modelBuilder.Entity("BHAMCApp.Models.FKMAMA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateVisit3")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("IDNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItajeQ4")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagementFK")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersQ1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemsDiagnosis")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q1")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q10")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q11")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q12")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q13")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q14")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q15")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q16")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q17")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q18")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q19")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q20")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q21")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q22")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q23")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q7")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q8")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q9")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("FKMAMA");
                });

            modelBuilder.Entity("BHAMCApp.Models.FKMTOTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date3Month")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("IDNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicationPres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemsDsis")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q10_a")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q10_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q10_c")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q10_d")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q10_e")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q11_a")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q11_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q11_c")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q12_a")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q12_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q12_c")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q13_a")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q13_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q13_c")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q13_d")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q13_e")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q13_f")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q14_a")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q14_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q14_c")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q14_d")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q14_e")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q14_f")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q14_g")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q15_a")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q15_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q15_c")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q15_d")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q15_e")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q15_f")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q15_g")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q15_h")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q16_a")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q16_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q16_c")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q1_a")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q1_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q1_c")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q2")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q3")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q3_a")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q3_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q4")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q5_1_a")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Q5_1_b")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q5_1_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_1_d")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_1_e")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_2_a")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Q5_2_b")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q5_2_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_2_d")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_2_e")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_3_a")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Q5_3_b")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q5_3_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_3_d")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_3_e")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_4_a")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Q5_4_b")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q5_4_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_4_d")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_4_e")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_5_a")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Q5_5_b")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q5_5_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_5_d")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q5_5_e")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q7_1")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_1_a")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_1_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q7_2")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_2_a")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_2_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q7_3")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_3_a")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_3_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q7_4")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_4_a")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_4_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q7_5")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_5_a")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_5_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q7_6")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_6_a")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_6_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q7_7")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_7_a")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_7_b")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q7_8")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Q7_8_a")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Q7_8_b")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q8")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q8_1")
                        .HasColumnType("TEXT");

                    b.Property<int>("Q9")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q9_1")
                        .HasColumnType("TEXT");

                    b.Property<int>("SexMt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Tarehe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TareheKuzaliwa")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("UmriMtotoMiezi")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("FKMTOTO");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BHAMCApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BHAMCApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BHAMCApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BHAMCApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
